from .views_locale import *
from .views_login_manager import *
from .views_pages import *
from .views_user import *
from .relationship.views_relationships import *
from .relationship.posts_relationships import *
from .views_match import *
from .views_chat import *
from .views_tournament import *
